### ISSUE TITLE
Browser crashes on record on Firefox 66.0.03 running on Windows 10

### ISSUE THREAD

**Issue by Nandhan-augment** [Ziggeo/angular-ziggeo#21] opened 2019-05-02 10:20 UTC
Video recorder not working in mozilla firefox66.0.03(windows10). Browser gets crashed after pressing record

**Comment by Bane-D** [comment] 2019-05-02 12:03
Hi Nandhan,

Can you please let us know what is the version of Angular SDK that you have tried this and just to confirm if it is something connected to Angular or not, can you please try recording in the same browser on the following page: https://ziggeo.com/video-recorder#demo and try recording a test video.

Bane

**Comment by Nandhan-augment** [comment] 2019-05-02 13:15
Hi,

"angular-ziggeo": "^1.0.2",
"ziggeo-client-sdk": "^2.33.4",

**Comment by Bane-D** [comment] 2019-05-02 13:23
Thank you Nandhan.

And can you tell me if it was crashing on https://ziggeo.com/video-recorder#demo as well?

This is just to know more about why it happens so that we can resolve it faster.

Thank you,
Bane

**Comment by Nandhan-augment** [comment] 2019-05-02 13:46
Hi Bane,

the link you have shared also crashed as well.

Thanks
Nandha

**Comment by Nandhan-augment** [comment] 2019-05-03 13:51
Hi,
any updates?

thanks
Nandha

**Comment by Nandhan-augment** [comment] 2019-05-06 14:49
Hi Bane,

Any updates?

**Comment by sambua** [comment] 2019-05-06 14:55
Hello @Nandhan-augment ,

Sorry for late respond, but we couldn't reproduce this error, with the latest FF version 66.0.3

Could you please advice if there's any console errors? And also will be very good if could record screen, if possible sure.

Thanks in advance

**Comment by Nandhan-augment** [comment] 2019-05-06 15:11
Hi,

i have attached a video and image.

**Comment by Bane-D** [comment] 2019-05-20 00:00
Hi Nandhan,

Just an update. We have tried to recreate it and was never able to recreate the same. As such we would need to see more of what is happening so I would like to ask you if you can upload the video to your Ziggeo account and share with us the video token?

* I do see that you have mentioned that you had uploaded video and image, however that is not really available to us.

Alternatively come to this issue and attach the file directly over GitHub.

The link to this issue is: https://github.com/Ziggeo/angular-ziggeo/issues/21

Thank you,
Bane

**Comment by Nandhan-augment** [comment] 2019-05-21 09:51
![2019-05-06_125629](https://user-images.githubusercontent.com/38003725/58086519-6f30c700-7bdc-11e9-94bd-b3512c09f381.jpg)


Hi,
here i have attached two video token:
6e8c25baeaa0342f0bed9b39895cdf4e
89acc85622df7ddd9a12f257633cff06

Thanks
Nandha

**Comment by sambua** [comment] 2020-04-22 14:06
Should be fixed with new versions of ZiggeoClientSDK

**Closed as completed by sambua** 2020-04-22 14:06 UTC
